### ISSUE TITLE
Authentication fails

### ISSUE THREAD

**Issue by timsueberkrueb** [tim-sueberkrueb/ubuntu-hangups#68]
> Google recently broke the previous login method, which involved logging
> in using a browser and copying an authorization code to hangups.

See https://github.com/tdryer/hangups/issues/260.

**Comment by StuntsPT** [comment]
This has been fixed (kind of) upstream, but now a new issue seems to [have arisen](https://github.com/tdryer/hangups/issues/265#issuecomment-250671353), which also affects ubuntu-hangups.
Just thought I should give you a heads up.

**Comment by timsueberkrueb** [comment]
@StuntsPT thanks for the heads up. I'm also concerned that the current fix will most probably stop working as soon as [Google blocks this kind of authentification](https://github.com/tdryer/hangups/issues/260#issuecomment-249088706) :|

**Comment by StuntsPT** [comment]
Google is being kind of "hostile" to 3rd party clients for their services lately.
I think we all knew this could happen eventually... but I for one was still hoping for a return to the old days of open protocols and APIs.
Let's keep working around these issues while we can, but I think it's time to start thinking of an alternative solution for IM.
Also, sorry about the off-topic!

**Comment by timsueberkrueb** [comment]
@StuntsPT no need to be sorry, that's not off-topic :) 

> I think we all knew this could happen eventually... but I for one was still hoping for a return to the old days of open protocols and APIs.

Yeah, I agree ...

**Comment by bittner** [comment]
Remember that we're not dealing with "Google" anymore. This is "Alphabet", and the mission of Alphabet is to increase revenue of all (ex-Google) companies in order to stay on top of the most profitable corporations world-wide:

>  We are excited about…
> - Getting more ambitious things done.
> - Taking the long-term view.
> - Empowering great entrepreneurs and companies to flourish.
> - Investing at the scale of the opportunities and resources we see.
> - Improving the transparency and oversight of what we’re doing.
> - Making Google even better through greater focus.
> - And hopefully… as a result of all this, improving the lives of as many people as we can.

(Source: view-source:https://abc.xyz/, lines 100+)

Bullet **3** probably refers to the _two founders of Google_ :smirk: and all _their companies_, the ones under Alphabet's umbrella, haha, bullet **5** refers to their internal controlling, i..e. financial transparency, and bullet **6** is again ... money! Ultimately, the number of _"as many ... as we can"_ in  **7** is probably very small.

This is fundamentally different to what we (developers?) know or knew Google for. This one here, at least, was my idea of Google in the 200x-ies (and I believe I was not alone):

> A home for hackers, awesome freedom and no worries about money to spend - for building cool software and a better future!

Well, good night dreams of the past. Today, we've got Alphabet. (Now this has _really_ gotten off-topic, sorry!)  :anguished: :weary:

**Comment by StuntsPT** [comment]
Back on topic:
[Hangups Issue #265](https://github.com/tdryer/hangups/issues/265), which was affecting ubuntu-hangups is now fixed in the latest release (0.4.1).
Can we get another rebuild of ubuntu-hangups with this new release to get it working again?
Thanks!

**Comment by timsueberkrueb** [comment]
@StuntsPT Work in progress.

**Comment by timsueberkrueb** [comment]
[Fix](https://github.com/tim-sueberkrueb/ubuntu-hangups/releases/tag/v0.3.5) released.
Two-factor authentication won't work for now.

**Comment by StuntsPT** [comment]
Awesome! It's working great now.
Thanks.
